version: '3.8'

services:
  rcontrol: 
    build:
      context: .
      dockerfile: rcontrol.dockerfile
    environment:
#      - FLASK_APP=application
      - PYTHONUNBUFFERED=1
    volumes:
      - ${PWD}:/opt/code
#    ports: 
#      - "5000:5000"
    command: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    volumes:
      - rcontrol_db:/var/lib/postgresql/data    
#      - ${PWD}:/opt/code
  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
      - ${PWD}/nginx/certbot/conf:/etc/letsencrypt
      - ${PWD}/nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: ["/bin/sh", "-c", "while :; do sleep 6h & wait $${!}; nginx -s reload; nginx -g \"daemon off\"; done"]
  certbot:
    image: certbot/certbot
    volumes:
      - ${PWD}/nginx/certbot/conf:/etc/letsencrypt
      - ${PWD}/nginx/certbot/www:/var/www/certbot
    #entrypoint: ["sleep", "12h"]
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"]

volumes:
  rcontrol_db: