version: '3.8'

services:
  rcontrol: 
    build:
      context: .
      dockerfile: rcontrol.dockerfile
    environment:
#      - FLASK_APP=application
      - PYTHONUNBUFFERED=1
    volumes:
      - ${PWD}:/opt/code
#    ports: 
#      - "5000:5000"
    command: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    volumes:
      - rcontrol_db:/var/lib/postgresql/data    
#      - ${PWD}:/opt/code
  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  rcontrol_db: