version: '3.8'

services:
  rcontrol: 
    build:
      context: .
      dockerfile: rcontrol.dockerfile
    environment:
#      - FLASK_APP=application
      - PYTHONUNBUFFERED=1
    volumes:
      - ${PWD}:/opt/code
    ports: 
      - "5000:5000"
    command: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    volumes:
      - rcontrol_db:/var/lib/postgresql/data    
#      - ${PWD}:/opt/code
  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d
      - ${PWD}/nginx/certbot/conf:/etc/letsencrypt
      - ${PWD}/nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: ["/bin/sh", "-c", "trap \"nginx -s stop; exit 0\" TERM; nginx ; while :; do sleep 6h & wait $${!}; nginx -s reload; done"]
    #command: ["/bin/sh", "-c", "sleep 12h"]
  certbot:
    image: certbot/certbot
    volumes:
      - ${PWD}/nginx/certbot/conf:/etc/letsencrypt
      - ${PWD}/nginx/certbot/www:/var/www/certbot
    #entrypoint: ["sleep", "12h"]
    entrypoint: ["/bin/sh", "-c", "trap \"exit 0\" TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"]
  postfix:
    build:
      context: .
      dockerfile: postfix.dockerfile
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
    volumes:
      - ${PWD}/postfix:/var/mail
    environment:
      - MY_DESTINATION=${MYDOMAIN}, localhost.localdomain, localhost
    ports:
      - "25:25"
  watchmail:
    build:
      context: .
      args:
        USERID: ${USERID}
        GROUPID: ${GROUPID}
      dockerfile: watchmail.dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ${PWD}:/opt/code
      - ${PWD}/postfix:/postfix

volumes:
  rcontrol_db: