"""empty message

Revision ID: 2e763066ec35
Revises: 4048da6c929d
Create Date: 2020-06-03 03:39:44.408083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e763066ec35'
down_revision = '4048da6c929d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rcommand', sa.Column('rec_date', sa.DateTime(), nullable=True))
    op.add_column('rcommand', sa.Column('rec_type', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rcommand', 'rec_type')
    op.drop_column('rcommand', 'rec_date')
    # ### end Alembic commands ###
