"""empty message

Revision ID: 4048da6c929d
Revises: 
Create Date: 2020-05-30 03:35:35.645533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4048da6c929d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rcommand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmd', sa.String(length=2), nullable=True),
    sa.Column('action', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rcommand')
    # ### end Alembic commands ###
