"""empty message

Revision ID: d5055c749353
Revises: 2e763066ec35
Create Date: 2020-06-08 10:01:29.558392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5055c749353'
down_revision = '2e763066ec35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rcommand', sa.Column('visit_ip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rcommand', 'visit_ip')
    # ### end Alembic commands ###
